In [1]:
#Assignment 1
import numpy as np
# Given list
Lst = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
# Convert the list into a NumPy array
arr = np.array(Lst)
# Replace odd elements with -2
arr[arr % 2 != 0] = -2
print(arr)


[[-2  2 -2]
 [ 4 -2  6]
 [-2  8 -2]]


In [3]:
#Assingment 2
import numpy as np
# Given array
arr = [1, 2, 3, 4, 5, 8, 9, 10, 12, 22, 32, 54, 99, 6, 7]
# Convert the list into a NumPy array
arr = np.array(arr)
# Print elements in the range from 8 to 15
print(arr[(arr >= 8) & (arr <= 15)])


[ 8  9 10 12]


In [7]:

#Assingment 3
import numpy as np
# Create a 3x3 array with numbers from 1 to 9
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# Swap columns 1 and 2
arr[:, [0, 1]] = arr[:, [1, 0]]
print(arr)


[[2 1 3]
 [5 4 6]
 [8 7 9]]


In [9]:
#Assingment 4
import numpy as np# Given array with NaN values
arr = np.array([[1.3, 2.5, 3.6, np.nan], 
                [2.6, 3.3, np.nan, 5.5], 
                [2.1, 3.2, 5.4, 6.5]])
# Calculate the column-wise mean, ignoring NaN values
col_means = np.nanmean(arr, axis=0)

# Find indices where NaN values are located
inds = np.isnan(arr)

# Replace NaN values with the column means
arr[inds] = np.take(col_means, np.where(inds)[1])

print(arr)


[[1.3 2.5 3.6 6. ]
 [2.6 3.3 4.5 5.5]
 [2.1 3.2 5.4 6.5]]


In [17]:
#Assingment 5
import numpy as np
# Given array
arr = np.array([[2, 4, 6], [1, 3, 5]])
# i. Convert the NumPy array into a NumPy matrix
matrix = np.matrix(arr)
# ii. Sort the values in the matrix
sorted_matrix = np.sort(matrix)
print("NumPy Matrix:")
print(matrix)
print("\nSorted Matrix:")
print(sorted_matrix)


NumPy Matrix:
[[2 4 6]
 [1 3 5]]

Sorted Matrix:
[[2 4 6]
 [1 3 5]]
