#Data Science
Study of Data
1. Collection of Data or Data Acquasition
2. Transfer this data in common format that you are using in Program ex:csv Data Transformation
3. Data Cleaning / PreProcessing i. Data Validation ii. Data Mising iii.Data Duplcation iv Data incorrect
4. Data Analysis
5. Data Visulization

Numpy Deals with Number only

In [10]:
import numpy as np 
numpy_L=np.arange(100000)

%timeit sum_val=np.sum(numpy_L)


131 μs ± 892 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [12]:
numpy_L =np.arange(100000)
numpy_L.itemsize * numpy_L.size

400000

In [26]:
arr=np.array([1,2,3,44,5])
arr

array([ 1,  2,  3, 44,  5])

In [28]:
type(arr)

numpy.ndarray

In [30]:
arr[0:2]

array([1, 2])

In [54]:
arr1=np.array([[11,2],[22,3],[1,7]])
arr1

array([[11,  2],
       [22,  3],
       [ 1,  7]])

In [56]:
arr1.dtype

dtype('int32')

In [58]:
arr1.ndim

2

In [64]:
arr1[1,0]

22

In [72]:
#arr1[1:3,0:2]   Array Slicing
arr1[0:3,0:2]

array([[11,  2],
       [22,  3],
       [ 1,  7]])

In [84]:
arr1[0:3,0:2]

array([[11,  2],
       [22,  3],
       [ 1,  7]])

In [18]:
import numpy as np
#different way of creating numpy array
#using zero function
arr=np.zeros([3,3],dtype=int)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [6]:
# using Ones function
arr1=np.ones([2,2])
print(arr1)

[[1. 1.]
 [1. 1.]]


In [8]:
# using empty data m
arr3=np.empty([3,2])
print(arr3)

[[2.07955588e-312 8.48798317e-313]
 [9.33678149e-313 9.97338022e-313]
 [1.24611673e-306 1.22387635e-307]]


In [28]:
#using existing data
L=[[1,2,3,4],[4,3,2,1]]
arr2=np.array(L)
# making copy of array
arr4=arr2 
arr2[0,1]=10
print(arr2)
print(arr4)

[[ 1 10  3  4]
 [ 4  3  2  1]]
[[ 1 10  3  4]
 [ 4  3  2  1]]


In [36]:
#copy of array
L=[[1,2,3,4],[4,3,2,1]]
arr2=np.array(L)
arr4=arr2.copy()
arr2[0,1]=10
print(arr2)
print()
print(arr4)

[[ 1 10  3  4]
 [ 4  3  2  1]]

[[1 2 3 4]
 [4 3 2 1]]


In [46]:
arr=np.arange(10)
print("array")
print(arr)
arr+2   # element by element operation
arr.size

array
[0 1 2 3 4 5 6 7 8 9]


10

In [55]:
arr1=np.arange(5)
arr2=np.arange(6,11)

print(arr1)
print(arr2)

arr1+arr2  # element by element operation

[0 1 2 3 4]
[ 6  7  8  9 10]


array([ 6,  8, 10, 12, 14])

In [69]:
narr1=np.array([[1,2],[3,4]])
narr2=np.array([[4,5],[8,2]])

print(narr1 * narr2)
print()
print(narr1.dot(narr2))

In [ ]:
# Universal Function 
1. Mathematical 
2. Trigonometry
3. bit dwiddling or bit manipulation
4. Floating function
5. Comparision

In [97]:
# MAthematical Function 
nar1=np.array([[4,5],[7,6]])
nar2=np.array([[2,3],[5,6]])
print(nar1)
print(nar2)
print(nar1+nar2)
np.add(nar1 ,nar2)

[[4 5]
 [7 6]]
[[2 3]
 [5 6]]
[[ 6  8]
 [12 12]]


array([[ 6,  8],
       [12, 12]])

In [101]:
print(np.subtract(nar1,nar2))

[[2 2]
 [2 0]]


In [105]:
np.lcm(nar1,nar2)

array([[ 4, 15],
       [35,  6]])

In [107]:
np.sqrt(nar1)

array([[2.        , 2.23606798],
       [2.64575131, 2.44948974]])

In [115]:
#Triginometry

tarr1=np.array([[2,1],[5,4]])
tarr1

print(np.sin(tarr1))
print(np.cos(tarr1))

[[ 0.90929743  0.84147098]
 [-0.95892427 -0.7568025 ]]
[[-0.41614684  0.54030231]
 [ 0.28366219 -0.65364362]]


In [123]:
#bit dwiddling or bit manipulation
barr1=np.array([[1,2],[2,1]])
barr2=np.array([[3,4],[4,3]])

print(np.bitwise_and(barr1,barr2))
print(np.bitwise_or(barr1,barr2))

[[1 0]
 [0 1]]
[[3 6]
 [6 3]]


In [135]:
#Comparision 
carr1=np.array([[3,1],[1,1]])
carr2=np.array([[4,6],[5,7]])
print(carr1<carr2)
a= np.arange(4).reshape(2,2)
a
np.greater(carr1,carr2)

[[ True  True]
 [ True  True]]


array([[False, False],
       [False, False]])

In [143]:
ar1=np.array([1.2,2.1,3.2,np.log(-1)])
ar1
np.isnan(ar1)
np.floor(ar1)


C:\Users\ABHAY\AppData\Local\Temp\ipykernel_12332\2633774437.py:1: RuntimeWarning: invalid value encountered in log
  ar1=np.array([1.2,2.1,3.2,np.log(-1)])


array([ 1.,  2.,  3., nan])

In [163]:
# Aggreation
arr=np.arange(1,10)
print(arr)
#Aggregate function
print(np.sum(arr))
print(np.mean(arr))
print(np.min(arr))
print(np.max(arr))
a22=[[3,4],[1,0]]
np.all(a22)  # all the value are non zero
np.any(a22)


[1 2 3 4 5 6 7 8 9]
45
5.0
1
9


True

In [187]:
a=np.arange(10,100,10)
a
ind=[0,3,4,8]  #fancy indexing
a[ind]

array([10, 40, 50, 90])

In [189]:
carr1=np.array([[3,1,2],[1,1,2]])
print(carr1)
print(carr1.ndim)
for i in np.nditer(carr1):
    print(i)

[[3 1 2]
 [1 1 2]]
2
3
1
2
1
1
2


In [203]:
carr1=np.array([[3,1,2],[1,1,2]])
print(carr1)
np.shape(carr1)
np.reshape(carr1,(3,2))

[[3 1 2]
 [1 1 2]]


array([[3, 1],
       [2, 1],
       [1, 2]])

In [207]:
# ravel convert 2,3 diimension array to 1 dimension 
carr1=np.array([[3,1,2],[1,1,2]])
carr1
np.ravel(carr1)

array([3, 1, 2, 1, 1, 2])

In [209]:
# transpose change Row to Coloumn and Viceversa
crr1=np.array([[3,1,2],[1,1,2]])
print(crr1)
np.transpose(crr1)

[[3 1 2]
 [1 1 2]]


array([[3, 1],
       [1, 1],
       [2, 2]])

In [223]:
crr1=np.array([[3,1,2],[1,1,2]])
crr2=np.array([[4,5,6],[7,8,9]])
np.concatenate((crr1,crr2),axis=1) # 0 row wise None - Flatten row

array([[3, 1, 2, 4, 5, 6],
       [1, 1, 2, 7, 8, 9]])

In [229]:
d=np.array([1,2,3])
d
d2=np.array([5,6,7])
d2
print(np.hstack((d,d2)))
print(np.vstack((d,d2)))


[1 2 3 5 6 7]


In [243]:
# Splitting array 
arrr=np.array([1,2,3,4,5,6,7,8])
print(arrr)
print(np.split(arrr,4))
are=np.reshape(arrr,(4,2))
np.hsplit(are,2)

[1 2 3 4 5 6 7 8]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


[array([[1],
        [3],
        [5],
        [7]]),
 array([[2],
        [4],
        [6],
        [8]])]

In [251]:
arr=np.arange(24).reshape(6,4)
arr
np.hsplit(arr,2)  # split coloumn wise
np.vsplit(arr,2)  # split horizontally

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [259]:
arary1=np.array([1,2,3,4,5,6,7,8,9])
print(arary1)
np.savetxt('Numpy_file.txt',arary1,delimiter=',')
arr=np.genfromtxt('Numpy_file.txt',delimiter=',')
print(arr)

[1 2 3 4 5 6 7 8 9]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [265]:
# opening and writing in binary mode 
fp=open('file1_bin.txt','ab+')
arr=np.array([[1,2],[3,4]])
print(arr)
np.save(fp,arr)


[[1 2]
 [3 4]]


In [267]:
fp.seek(0)
arr=np.load(fp)
print(arr)

[[1 2]
 [3 4]]
