NumPy - Numeric Python
it deal with only numbers

In [1]:
%%timeit
a=range(100000)
b=range(100000)
c=[]
for i in range(len(a)):
    c.append(a[i]*b[i])

104 ms ± 805 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
%%timeit
import numpy as np
a=np.arange(100000)
b=np.arange(100000)

c= a * b

802 μs ± 11.2 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [7]:
import numpy as np
a=np.array([10,20,30])
a
print(a[0])
print(a[0:2])
print(a.dtype)
print(a.size)
print(a.itemsize)
print(a.shape)

10
[10 20]
int32
3
4
(3,)


In [8]:
a2=np.array([[10,20,30],[40,50,60]])
print(a2.ndim)
print(a2.shape)
print(a2[0][1])
print(a2[0,1])
print(a2[0:2,0:2])
print(a2[0:2,1:3])

2
(2, 3)
20
20
[[10 20]
 [40 50]]
[[20 30]
 [50 60]]


In [9]:
ls=[1,2,3,4,5,6,7,8,9]
a2=np.array([[10,20,30,22],[40,50,60,33]])
print(ls[0:3])
print(ls[::-1])
print(a2[0:2,1:3])

[1, 2, 3]
[9, 8, 7, 6, 5, 4, 3, 2, 1]
[[20 30]
 [50 60]]


In [10]:
for i in np.nditer(a2):
    print(i)


10
20
30
22
40
50
60
33


'''
Universal function
Mathematic operation
Trignometry operation
Bit tewdlling operation
Comparision operation
'''

In [11]:
#element by element operation default function
a12=np.array([1,2,3])
a12 * 2

array([2, 4, 6])

In [12]:
a22=np.array([[11,22,33,44],[55,66,77,88]])
print(a2)
a2 + a22
np.add(a2,a22)

[[10 20 30 22]
 [40 50 60 33]]


array([[ 21,  42,  63,  66],
       [ 95, 116, 137, 121]])

In [13]:
a2 > a22

array([[False, False, False, False],
       [False, False, False, False]])

In [14]:
print(np.sin(a12))
print(np.cos(a12))
print(np.greater(a2,a22))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[[False False False False]
 [False False False False]]


In [15]:
np.where(a2==True)

(array([], dtype=int64), array([], dtype=int64))

In [16]:
a2

array([[10, 20, 30, 22],
       [40, 50, 60, 33]])

In [17]:
np.isreal(a12)

array([ True,  True,  True])

In [18]:
ad=np.array([np.nan,11,44,np.nan,55,66])
np.isnan(ad)

array([ True, False, False,  True, False, False])

In [19]:
ad

array([nan, 11., 44., nan, 55., 66.])

In [20]:
a11=np.array([[1,2],[2,3]])
a13=np.array([[2,4],[1,2]])
np.bitwise_or(a11,a13)

array([[3, 6],
       [3, 3]])

In [21]:
alog=np.array([[1,2],[3,0]])
np.all(alog)
np.any(alog)

True

In [22]:
print(ls)
print(np.max(ls))
print(np.sum(ls))

[1, 2, 3, 4, 5, 6, 7, 8, 9]
9
45


In [23]:
#ravel converting any multi dimenssion array to one dimensiona
a11

array([[1, 2],
       [2, 3]])

In [24]:
a11.ravel()

array([1, 2, 2, 3])

In [25]:
np.shape(a11)

(2, 2)

In [26]:
np.array_split(ls,2)

[array([1, 2, 3, 4, 5]), array([6, 7, 8, 9])]

In [27]:
ls

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [28]:
print(a13)
np.vsplit(a13,2)

[[2 4]
 [1 2]]


[array([[2, 4]]), array([[1, 2]])]

In [29]:
a13
np.hsplit(a13,2)

[array([[2],
        [1]]),
 array([[4],
        [2]])]

In [30]:
np.concatenate((a11,a13),axis=0)

array([[1, 2],
       [2, 3],
       [2, 4],
       [1, 2]])

In [31]:
print(np.stack((a11,a13)))

[[[1 2]
  [2 3]]

 [[2 4]
  [1 2]]]


In [32]:
a13

array([[2, 4],
       [1, 2]])

In [33]:
np.vstack((a11,a13))

array([[1, 2],
       [2, 3],
       [2, 4],
       [1, 2]])

In [34]:
np.save('BinFile',a13)

In [35]:
a=np.load('BinFile.npy')
a

array([[2, 4],
       [1, 2]])

In [36]:
np.savetxt('NumpySave',a11)

In [37]:
c=np.loadtxt('NumpySave')
c

array([[1., 2.],
       [2., 3.]])

In [276]:
np.ones((3,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [282]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])