In [1]:
#Assignment 1
import pandas as pd
import numpy as np

# Load the CSV file into a Pandas DataFrame
df = pd.read_csv('SalaryGender.csv')

# Check the first few rows to understand the structure
print(df.head())

# Extract each column into a separate NumPy array
salary_array = np.array(df['Salary'])   # Assuming 'Salary' is a column name
gender_array = np.array(df['Gender'])   # Assuming 'Gender' is a column name
# Add more columns as needed based on the CSV structure, e.g.,
# another_column_array = np.array(df['AnotherColumn'])

# Print the arrays to verify
print("Salary Array:", salary_array)
print("Gender Array:", gender_array)


   Salary  Gender  Age  PhD
0   140.0       1   47    1
1    30.0       0   65    1
2    35.1       0   56    0
3    30.0       1   23    0
4    80.0       0   53    1
Salary Array: [140.    30.    35.1   30.    80.    30.    60.    31.1  125.    51.
   3.    46.   150.     3.   130.    15.   130.    84.   190.    74.
  73.    10.    50.     7.     9.5   15.2   28.6   20.    72.    81.
 100.    90.    90.    35.    30.    25.    52.     9.    63.    72.
  16.    92.   106.     2.5    9.    32.    32.    55.    52.    28.
  20.    14.7   22.3   34.8   84.    19.   160.    65.    55.     4.6
 102.    20.    62.    55.    45.6   40.    24.    35.    48.    20.
  40.7   15.     0.25 152.    39.8   12.    30.   120.     1.7   36.
  96.    38.    90.     9.    25.8   22.    38.8   72.    89.    41.
  89.    25.    52.   115.    66.    18.6  152.     1.8   35.     4.  ]
Gender Array: [1 0 0 1 0 0 1 0 1 1 1 1 1 1 1 0 1 0 1 1 0 0 0 0 0 1 1 0 0 1 0 0 0 1 0 1 0
 0 1 1 1 0 1 1 0 0 0 1 1 0 0 0 1 0 

In [2]:
# Assingment 2
import pandas as pdSalaryGender

# Load the CSV file into a Pandas DataFrame
df = pd.read_csv('SalaryGender.csv')

# Check the first few rows to understand the structure
print(df.head())

# Filter data for men with a Ph.D.
men_phd=df[(df['Gender']==1) & (df['PhD'] == 1) ]
women_with_phd = df[(df['Gender'] == 0) & (df['PhD'] == 1)]

# Count the number of men and women with a Ph.D.
num_men_with_phd = len(men_phd)
num_women_with_phd = len(women_with_phd)

# Print the results
print(f"Number of men with a Ph.D.: {num_men_with_phd}")
print(f"Number of women with a Ph.D.: {num_women_with_phd}")




   Salary  Gender  Age  PhD
0   140.0       1   47    1
1    30.0       0   65    1
2    35.1       0   56    0
3    30.0       1   23    0
4    80.0       0   53    1
Number of men with a Ph.D.: 24
Number of women with a Ph.D.: 15


In [ ]:
#Assingement 3

import pandas as pd

# Load the CSV file into a Pandas DataFrame
df = pd.read_csv('SalaryGender.csv')

# Check the first few rows to understand the structure
print(df.head())

# Filter the data to keep only people with a Ph.D.
df_phd = df[df['PhD'] == 1]

# Select only the "Age" and "Ph.D." columns
df_phd_selected = df_phd[['Age', 'PhD']]

# Display the new DataFrame with Age and Ph.D. columns
print(df_phd_selected)

# Now, remove rows of people who don't have a Ph.D. from the original DataFrame
df = df[df['PhD'] == 1]

# Save the modified DataFrame back to a new CSV (optional, if you want to overwrite or save the updated file)
df.to_csv('filtered_salary_gender.csv', index=False)

# Show the updated DataFrame (optional)
print(df.head())


In [57]:
#Assingment 4
import pandas as pd

# Load the CSV file into a Pandas DataFrame
df = pd.read_csv('SalaryGender.csv')

# Check the first few rows to understand the structure
#print(df.head())

# Filter the data for people who have a Ph.D.
phd_people = df[df['PhD'] == 1]

# Calculate the total number of people with a Ph.D.
total_phd = len(phd_people)
print(phd_people.head())
# Print the result
print(f"Total number of people with a Ph.D.: {total_phd}")


   Salary  Gender  Age  PhD
0   140.0       1   47    1
1    30.0       0   65    1
4    80.0       0   53    1
8   125.0       1   44    1
9    51.0       1   63    1
Total number of people with a Ph.D.: 39


In [59]:
#Assignement 5
import numpy as np

# Define the array
arr = [0, 5, 4, 0, 4, 4, 3, 0, 0, 5, 2, 1, 1, 9]

# Use np.bincount() to count the frequency of each value
frequency = np.bincount(arr)

# Print the result
print(frequency)


[4 2 1 1 3 2 0 0 0 1]


In [61]:
#Assingment 6
import numpy as np

# Create the NumPy array
arr = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])

# Filter the elements greater than 5
filtered_arr = arr[arr > 5]

# Print the filtered array
print(filtered_arr)


[ 6  7  8  9 10 11]


In [63]:
#Assigment 7

import numpy as np

# Create a NumPy array with NaN values
arr = np.array([np.nan, 1., 2., np.nan, 3., 4., 5.])

# Print the original array
print("Original array:")
print(arr)

# Filter the array to omit NaN values
filtered_arr = arr[~np.isnan(arr)]

# Print the filtered array
print("\nArray with NaN values omitted:")
print(filtered_arr)


Original array:
[nan  1.  2. nan  3.  4.  5.]

Array with NaN values omitted:
[1. 2. 3. 4. 5.]


In [68]:
#Assingment 8
import numpy as np

# Create a 10x10 array with random values between 0 and 1
random_array = np.random.rand(10, 10)

# Find the minimum and maximum values
min_value = np.min(random_array)
max_value = np.max(random_array)

# Print the array, minimum, and maximum values
print("Random 10x10 Array:")
print(random_array)

print("\nMinimum Value:", min_value)
print("Maximum Value:", max_value)



Random 10x10 Array:
[[0.0411986  0.34499794 0.3409324  0.26105746 0.83521229 0.99450734
  0.38049964 0.16282282 0.59653808 0.58641743]
 [0.52098566 0.350873   0.16198316 0.7785686  0.39791036 0.54123293
  0.88093972 0.02579868 0.79990396 0.42957519]
 [0.47151373 0.45067336 0.80765563 0.45796763 0.73109473 0.64002831
  0.67185084 0.82610705 0.56548591 0.47252851]
 [0.69742022 0.38662279 0.46775983 0.94035895 0.26172307 0.20651235
  0.71856745 0.68254537 0.56940361 0.4349773 ]
 [0.83682513 0.09249872 0.24611298 0.77271752 0.26683788 0.27336588
  0.08369925 0.70397428 0.61486293 0.4789823 ]
 [0.03521305 0.18702108 0.49196244 0.19219734 0.12112369 0.43378457
  0.14651761 0.62417042 0.70594859 0.36815349]
 [0.59698301 0.85290093 0.40889112 0.21358689 0.45505209 0.02359802
  0.50087783 0.31348621 0.33215718 0.00197863]
 [0.05958695 0.75609751 0.74354259 0.75797713 0.77661404 0.996468
  0.18129261 0.22549217 0.7010018  0.29463518]
 [0.95143254 0.91927075 0.56413315 0.81722817 0.06950044 0.867

In [70]:
#Assigment 9
import numpy as np

# Create a random vector of size 30
random_vector = np.random.rand(30)

# Calculate the mean value of the vector
mean_value = np.mean(random_vector)

# Print the random vector and its mean value
print("Random Vector:")
print(random_vector)

print("\nMean Value:", mean_value)


Random Vector:
[0.51249335 0.15809746 0.82240646 0.78388206 0.82236367 0.88299393
 0.46782586 0.9174279  0.58455676 0.39839513 0.50981975 0.11571697
 0.47690785 0.77195994 0.92231228 0.57079367 0.80452836 0.93381708
 0.30883371 0.67014219 0.26739803 0.25801865 0.83060981 0.8022402
 0.58262471 0.8572913  0.47522581 0.32428345 0.80838193 0.72467478]

Mean Value: 0.6122007681314516


In [74]:
#Assigment 10

import numpy as np

# Create a NumPy array with elements from 0 to 10
arr = np.arange(11)

# Negate elements between 3 and 9 (exclusive)
arr[(arr > 3) & (arr < 9)] *= -1

# Print the modified array
print("Modified Array:")
print(arr)


Modified Array:
[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


In [76]:
#Assingment 11
import numpy as np

# Create a random 3x3 array
arr = np.random.rand(3, 3)

# Print the original array
print("Original Array:")
print(arr)

# Sort by the first column
sorted_by_first = arr[arr[:, 0].argsort()]

# Sort by the second column
sorted_by_second = arr[arr[:, 1].argsort()]

# Sort by the third column
sorted_by_third = arr[arr[:, 2].argsort()]

# Print the sorted arrays
print("\nSorted by First Column:")
print(sorted_by_first)

print("\nSorted by Second Column:")
print(sorted_by_second)

print("\nSorted by Third Column:")
print(sorted_by_third)

Original Array:
[[0.48206582 0.72629411 0.19140164]
 [0.27202527 0.14931673 0.22368115]
 [0.18400166 0.81112649 0.34039693]]

Sorted by First Column:
[[0.18400166 0.81112649 0.34039693]
 [0.27202527 0.14931673 0.22368115]
 [0.48206582 0.72629411 0.19140164]]

Sorted by Second Column:
[[0.27202527 0.14931673 0.22368115]
 [0.48206582 0.72629411 0.19140164]
 [0.18400166 0.81112649 0.34039693]]

Sorted by Third Column:
[[0.48206582 0.72629411 0.19140164]
 [0.27202527 0.14931673 0.22368115]
 [0.18400166 0.81112649 0.34039693]]


In [78]:
#Assigment 12
import numpy as np

# Create a 4D array (e.g., shape (2, 3, 4, 5))
arr = np.random.rand(2, 3, 4, 5)

# Print the original 4D array
print("Original 4D Array:")
print(arr)

# Compute the sum over the last two axes (axes 2 and 3)
sum_over_last_two_axes = np.sum(arr, axis=(2, 3))

# Print the result of the summation
print("\nSum over the last two axes:")
print(sum_over_last_two_axes)


Original 4D Array:
[[[[0.08029211 0.68268701 0.49995981 0.86979724 0.79178598]
   [0.23577671 0.52358714 0.64569871 0.88406265 0.89668367]
   [0.94180078 0.77178416 0.68395885 0.94461912 0.20705374]
   [0.38825495 0.40577711 0.67371084 0.61563004 0.97838212]]

  [[0.30086014 0.98167331 0.57433426 0.02840346 0.47910312]
   [0.48881267 0.18619409 0.21750332 0.77626945 0.77194338]
   [0.04656567 0.82741788 0.110574   0.78191168 0.03658718]
   [0.91951457 0.09877738 0.87771024 0.13330699 0.95155449]]

  [[0.43406424 0.50679762 0.98911496 0.40563629 0.30921494]
   [0.27240914 0.75349368 0.04300486 0.40794879 0.86853169]
   [0.22827122 0.05592315 0.15126502 0.14689474 0.40715176]
   [0.66620401 0.08969643 0.42481859 0.09969077 0.63177431]]]


 [[[0.74135024 0.91457263 0.12956562 0.33747289 0.71666502]
   [0.56052433 0.73823137 0.5574924  0.81213011 0.8875514 ]
   [0.94431447 0.32764795 0.5141791  0.8676906  0.83709783]
   [0.82012731 0.67804822 0.08765808 0.71795192 0.20648698]]

  [[0.35360

In [80]:
#Assigmnet 14
import numpy as np

# Create a random 5x5 array
arr = np.random.rand(5, 5)

# Print the original array
print("Original Array:")
print(arr)

# Swap row 1 (index 0) with row 3 (index 2)
arr[[0, 2]] = arr[[2, 0]]

# Print the modified array
print("\nArray after swapping rows 1 and 3:")
print(arr)


Original Array:
[[0.46136384 0.29864039 0.80472842 0.93830933 0.95999892]
 [0.51111481 0.88325257 0.78600864 0.11379818 0.6906728 ]
 [0.78746683 0.22503615 0.42213597 0.52799958 0.94139568]
 [0.10696023 0.62059283 0.47213523 0.54468391 0.46929691]
 [0.67567894 0.01580542 0.63184247 0.61107084 0.63220143]]

Array after swapping rows 1 and 3:
[[0.78746683 0.22503615 0.42213597 0.52799958 0.94139568]
 [0.51111481 0.88325257 0.78600864 0.11379818 0.6906728 ]
 [0.46136384 0.29864039 0.80472842 0.93830933 0.95999892]
 [0.10696023 0.62059283 0.47213523 0.54468391 0.46929691]
 [0.67567894 0.01580542 0.63184247 0.61107084 0.63220143]]


In [83]:
#Assignmet 15

import numpy as np

# Create a random 4x4 matrix
matrix = np.random.rand(4, 4)

# Print the original matrix
print("Original Matrix:")
print(matrix)

# Compute the rank of the matrix
rank = np.linalg.matrix_rank(matrix)

# Print the rank
print("\nRank of the Matrix:", rank)


Original Matrix:
[[0.33955039 0.82590524 0.99812838 0.00798839]
 [0.37956596 0.60450577 0.62280735 0.83253781]
 [0.78190857 0.73821478 0.62395424 0.21910278]
 [0.13124894 0.72191707 0.13954059 0.45812   ]]

Rank of the Matrix: 4
